### ISSUE TITLE
No confirmation mail on dolserver.net 

### ISSUE THREAD

**Issue by NetDwarf** [Dawn-of-Light/DOLSharp#157]
Hello,

I know this does not belong here, yet I don't really see another option reaching out. 

The problem is that new accounts don't get confirmation e-mails and you don't get an e-mail to your known mail account if you forgot your password (which is the case for me). 

Kind regards :)

**Comment by dol-leodagan** [comment]
I have the project of moving dolserver.net hosting to a Docker Container on one of my VPS, but I lack some free time to make sure everything is backup properly...

To sum up, it's a known bug !

**Comment by NetDwarf** [comment]
Seems like a pretty critical bug. What is the regular way now to reset password/create new account?

**Comment by dol-leodagan** [comment]
Contact an Administrator or Moderator through Discord, ask them for a temporary password, then log-in and change back your password to your preferred value.

I have to admit that the board is completely broken right now...

**Comment by NetDwarf** [comment]
This is kind of solved and kind of isn't, but I mark it as solved for now.
