### ISSUE TITLE
1.126 support

### ISSUE THREAD

**Issue by kjkrum** [Dawn-of-Light/DOLSharp#205]
I hacked in 1.126 support by adding a packet lib that extends 1.125 without changing anything. The client does not react to DoL's crypt key response. Is there any knowledge of what changed in 1.126, or plans to support it?

**Comment by kjkrum** [comment]
I remembered that I used the 1.109 game.dll when I had 1.125 it working before. BTW, I would ask my dumb questions on the forum, but it's not sending account confirmation emails.

**Comment by Graveen** [comment]
Sorry, you can try discord for account activation. AFAIK nothing is done for supporting recent game.dll

**Comment by benfalk** [comment]
You need to have an updated launcher for 1.126 @kjkrum

**Comment by kjkrum** [comment]
@Graveen Still not activated. Where do I find the discord?

**Comment by Graveen** [comment]
@kjkrum https://discord.gg/pSe9Hv
