### ISSUE TITLE
Heretic Focus Damage spells behavior different on live

### ISSUE THREAD

**Issue by NetDwarf** [Dawn-of-Light/DOLSharp#222]
Hello, 

I am currently poking around a bit in the Heretic spell code. First of all I want to lay out what I found out on Live so it is at least clear what has to be done.

tl;dr:
1. damage growth for each successive tick is m * ( 1 + growthrate * (n-1) ) where m is base damage and n is the number of (successive) focus ticks
2. resists do not have an influence on the damage of following ticks
3. the focus ends after a certain duration
4. growth is 50% for all damage focus spells but the uninterruptable where it is 60%
5. there is a growth cap which can not be exceeded by more successive ticks

**Current/wrong state:**
Example 1:
`1. tick: 100 Damage`
`2. tick: 125 Damage`
`3. tick: 156 Damage`
`4. tick: 195 Damage`
and so on ... so the damage is roughly m*1.25^n-1 where n is the number of ticks and m is the damage on first tick before variance.

Example 2:
`1. tick: 100 Damage`
`2. tick: Resist //lowers effective damage by 25%`
`3. tick: 93 Damage`
here we see that the addition and subtraction is not symmetric. 1*(1+0.25)*(1-0.25) ≠ 1

**Same examples on Live:** (assuming 100 base damage and 25% growth)
Example 1: 
`1. tick: 100 Damage`
`2. tick: 125 Damage`
`3. tick: 150 Damage`
`4. tick: 175 Damage`
This is more of an extrapolation of the Live behavior. There is no spell with this growth and start damage, but the pattern is the same. Damage difference is always from the delve multiplied by growth rate (on Live you see 50% or 60%)

Example 2:
`1. tick: 100 Damage`
`2. tick: Resist //implicitly 25 damage added to 125`
`3. tick: 150 Damage`
Resists do not stagnate or even lower the damage, but increase it implicitly for the next tick. The 3rd tick does 150 Damage regardless of resists if it is not resisted itself.

Example 3: (growth_cap of 60%)
`1. tick: 100 Damage`
`2. tick: Resist //implicitly 25 damage added to 125`
`3. tick: 150 Damage`
`4. tick: 160 Damage // (60%+100%)*initialDamage`
`5. tick: 160 Damage` 

Another thing to mention is duration. The focus stops after a certain duration (or number of ticks if you will) and this duration is even affected by spell duration (surprised me). 

This is not exhaustive, so I will add some additional problems as well.

**Comment by NetDwarf** [comment]
My approach will be to add 3 fields in the data base for the Focus spells for growth, growth_cap and duration. I am not sure if I add a default behavior at all. Maybe I should because servers probably won't start or spells will not work if it expects a value from a field.

**Comment by Graveen** [comment]
if you reuse some existing fields, this will be ok. if theses fields are empty (or at least one), you can use fallback generic hardcoded values. Basically, the resist issue (example 2) is something you can adress directly as there is no need to keep a wrong implementation.

**Comment by NetDwarf** [comment]
The exponential growth and no duration limit I also consider a bug. At least 1. 2. and 5. are working already here. Only thing I did not yet implement in 1. is a default growth (it's zero in my current implementation). Another sane default growth would be 50% I think. For a default growth_cap I have no idea. Either setting it to what it was before (unlimited) or zero or something in the range of 150%-400% (values that exist on Live). 

Since Heretic is notoriously buggy and nobody played it I think, I would say to really zero the defaults. If someone notices the subpar behavior they can notify the admin and if not it doesn't matter anyway. This has the advantage of not cluttering the code with legacy behavior. I can make a PR on EoD/db-public for correct values.
