### ISSUE TITLE
guild invites can't be send by guild leader

### ISSUE THREAD

**Issue by PeterV1982** [Dawn-of-Light/DOLSharp#248]
i'm the founder and guild leader
but when i try to invite an alt to my guild it says not high enough (and i'm rank 0)

**Comment by NetDwarf** [comment]
Hello, thank you for your issue submission!

When trying to replicate the issue I was actually able to invite. Can you check `/gc ranks` that you indeed have the permission to invite? If that's the case, I need more information like realm of characters involved and server (or relevant guild server settings if custom).

Kind regards,

Yay

**Comment by PeterV1982** [comment]
Well rank 0 has no rights to do anything

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: NetDwarf <notifications@github.com>
Verzonden: Tuesday, September 15, 2020 9:34:24 AM
Aan: Dawn-of-Light/DOLSharp <DOLSharp@noreply.github.com>
CC: PeterV1982 <petervermeulen1982@hotmail.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Dawn-of-Light/DOLSharp] guild invites can't be send by guild leader (#248)


Hello, thank you for your issue submission!

When trying to replicate the issue I was actually able to invite. Can you check /gc ranks that you indeed have the permission to invite? If that's the case, I need more information like realm of characters involved and server (or relevant guild server settings if custom).

Kind regards,

Yay

**Comment by NetDwarf** [comment]
Can you change the permissions for your rank? If I remember correctly rank 0 should be guild leader and therefore should be able to change permissions for a given rank.

**Comment by FlintTards** [comment]
On storm live like - it’s the same problem. 

I’ve tried several things. 

Creating a new guild gives you the opportunity to use /gc commands

But, once you relog/quit the game. And login Again, then your privileges is reset. And you can no longer use /gc commands. 

Really weird. 

(See my error submit under storm github)

**Comment by NetDwarf** [comment]
That sounds like a different error. I will test that later.

**Comment by PeterV1982** [comment]
Ok if you want i Will be in game later and i can log in anything. I know i had all permissions set before the crash could be it’s related?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: NetDwarf <notifications@github.com>
Verzonden: Tuesday, September 15, 2020 2:37:31 PM
Aan: Dawn-of-Light/DOLSharp <DOLSharp@noreply.github.com>
CC: PeterV1982 <petervermeulen1982@hotmail.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Dawn-of-Light/DOLSharp] guild invites can't be send by guild leader (#248)


That sounds like a different error. I will test that later.

**Comment by NetDwarf** [comment]
I could already replicate it. Still looking for the error.

**Comment by PeterV1982** [comment]
In About an hour i’ll be in Line i’ll give a schout in /irc will be in elleva

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: NetDwarf <notifications@github.com>
Verzonden: Tuesday, September 15, 2020 6:31:18 PM
Aan: Dawn-of-Light/DOLSharp <DOLSharp@noreply.github.com>
CC: PeterV1982 <petervermeulen1982@hotmail.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Dawn-of-Light/DOLSharp] guild invites can't be send by guild leader (#248)


I could already replicate it. Still looking for the error.
