### ISSUE TITLE
Xp Issues

### ISSUE THREAD

**Issue by Scrubtasticx** [Dawn-of-Light/DOLSharp#262]
Fresh compile of DOLserver and fresh DB from github when new char is made their xp stays at 100% and they keep leveling no mobs killed at all
client 1.125

**Comment by NetDwarf** [comment]
Can't reproduce. Just created a char and leveled to L2 and it behaves just as expected. It sounds like you got a humongous amount of XP which grants you several levels.

**Comment by Scrubtasticx** [comment]
ya its odd fresh DB fresh server no changes made to server props does it everytime

**Comment by Scrubtasticx** [comment]
Ok i figured it out its one of my custom scripts. just removed the customNPC folder and its not doing it thanks
