### ISSUE TITLE
1.125 Client spell tool tips

### ISSUE THREAD

**Issue by Scrubtasticx** [Dawn-of-Light/DOLSharp#263]
On client 1125 all the spell tooltips say all spells are level 1 and they don't say how much damage or runspeed % they do now.

Combat skills are fine its just spells

P.S. They work on Los-Ojo's repo say maybe somthing was missed on merge?

**Comment by tegstewart** [comment]
I've noticed some weirdness with multiple spells at the same level not working on 1.125 as well.

**Comment by DigitalBox98** [comment]
Same behavior noticed on spells tooltip :)
