### ISSUE TITLE
Name Generator

### ISSUE THREAD

**Issue by niothiel** [Dawn-of-Light/DOLSharp#32]
Hello,

I'm looking for the name generator code that powers the initial character creation screen. For some reason I recall seeing it in the source, but I can't seem to find it.. Could anyone point me in the right direction?

If this is done client-side, my apologies, feel free to close this issue.

Thanks!

-niothiel

**Comment by dol-leodagan** [comment]
Hello,

I can't remember if we had such generator server-side anytime in the project but we don't have this feature around now...

Character Creation Name Generator is totally client-side, no network packet are exchanged during the process, and you can even get duplicated Character Name before you submit it to the server !

**Comment by niothiel** [comment]
You're right, it actually is being done client side. After downloading the client I found out that the list of prefixes used for name generation is located at `<install dir>\charman\names.dat`. Thanks for the quick response.
