### ISSUE TITLE
Discord link down on README.md

### ISSUE THREAD

**Issue by ArThoX** [Dawn-of-Light/DOLSharp#421]
![image](https://user-images.githubusercontent.com/551029/203860474-f8c73cc6-0cde-4315-8f9d-a597324caf98.png)
(https://discord.gg/CXk6zpgwqp)

The Discord link is invalid. Cannot say if the Discord channel was removed or the link is just wrong ?

**Comment by DigitalBox98** [comment]
It’s working fine on my side, which error have you ?

**Comment by ArThoX** [comment]
![Screenshot_20221125_125222](https://user-images.githubusercontent.com/551029/203980906-8596ce8d-5cb5-4fd4-9180-5ed450ebd003.jpg)

**Comment by NetDwarf** [comment]
Can confirm this. It seems to have been expired. 

Try this one: https://discord.gg/dnGJeHRqyf

**Comment by ArThoX** [comment]
Confirmed: link working.

![image](https://user-images.githubusercontent.com/551029/204040291-465a38ae-1de0-4466-bc45-7179b2d08d1b.png)

**Comment by NetDwarf** [comment]
Okay, I close the issue then. Thank you reporting!
