### ISSUE TITLE
Spell icons update when levelling up (packet issues) or when talking with merchants

### ISSUE THREAD

**Issue by Lord-Seithenin** [Dawn-of-Light/DOLSharp#456]
Hello,
I think there is a small issue with packets when a player is levelling up (or leveling his training) because spell icons are not updated on the spell bars. (unless the player disconnects)
For example we have a druid level 5 having in "Nurture" spell list spells like Strenght of the Oak, Oak's Stoutness... etc
Let's level up the druid to level 20 "vigor of the redwood" replaces "Strenght of the Oak", obviously, but the icon isn't updated in the spell bar.
I think those icons were uptating themselves with the version 1.109 of the game.dll. but with recent versions it seems that it doesn't work.

Same issue when for exemple a player checks an item with procs/spell in his inventory then talks to a merchant all items sold "seems" to have the same procs/spells and show their icons. Same if you talk to another merchant, and this as long as the player hasn't selected another item in his inventory that has no spell/procs.

Here's a video showing the issues :
https://youtu.be/UdxK5PonLPg

**Comment by Lord-Seithenin** [comment]
Apparently the issue shows as well with the vault keeper when clicking on items in the list.

**Comment by NetDwarf** [comment]
The issue with the icons not changing seems to be live-like unfortunately. I tried to circumvent it but to no avail. I suspect it's a client side bug.

**Comment by NetDwarf** [comment]
The second issue with procs on the merchant is also present on Live. Unexpected.
