### ISSUE TITLE
Pet brains use hardcoded spells

### ISSUE THREAD

**Issue by tegstewart** [Dawn-of-Light/DOLSharp#73]
Currently, most of the pet brains (underhill is an exception) have hardcoded lists of spells they can use.  They won't cast new spells added to them in the DB.

I intend to fix this myself, but wanted to have it here as a reminder, but if it isn't resolved in six months it's safe to assume I've been hit by a car and somebody else should do it.

**Comment by tegstewart** [comment]
I've done a little looking into this, and a bunch of specific pet behaviours are hardcoded to only use certain types of spells or ability.  Things like CheckSpells() being overloaded to be {return false;} for BD pets that don't typically have spells.

I suspect this was done to save cpu time, but it limits being able to change pets by adding new content to them via the DB.  It seems to me that all the hard coding should be removed.

Thoughts?

**Comment by Graveen** [comment]
They must be removed. But iirc the spells are listed in the npctemplate ?

**Comment by tegstewart** [comment]
The NPCTemplate assigns spells to the pets, but the pet brains only let them use very specific ones or don't let them use any at all.

Most of that is unnecessary, but a few of the overloaded methods like the heal and buffer pets do need custom code, I just need to tweak them to be more general case and/or call the base method.

It's not urgent, so I'm leaving the issue here to remind me to come back to it.

**Comment by tegstewart** [comment]
I'm working on a bunch of changes to mobs and pets, so I'm closing this.
