### ISSUE TITLE
Stable Merchants don't accept some tickets

### ISSUE THREAD

**Issue by tegstewart** [Dawn-of-Light/DOLSharp#77]
When a quest gives a ticket for a horse ride, the stable master won't accept it.

I suspect this has to do with stable merch behaviour checking for hardcoded values, but might be quest scripts hardcoding stuff instead.

Edit:  Looks like some stable masters don't accept some of their own tickets, either.

**Comment by Loki1976** [comment]
Doesn't this happen if there is no horse route defined?

**Comment by tegstewart** [comment]
Done.
